id = "void"
name = "Dracula"
version = "0.1.0"
schema_version = 1
authors = ["Saul Espinoza Ruiz <CuentaPrincipalSaul@hotmail.com>"]
description = "A full dark theme for Zed"
repository = "https://github.com/SaulEspinozaRuiz/void-theme-zed"
